services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JtcSolutions\CodeGenerator\Service\Provider\ContextProvider:
    arguments:
      $controllerNamespaceTemplate: '%jtc_solutions_code_generator.global.controller_namespace_template%'
      $dtoNamespaceTemplate: '%jtc_solutions_code_generator.global.dto_namespace_template%'
      $projectDir: '%kernel.project_dir%'
      $projectBaseNamespace: 'Project'
      $errorResponseClass: 'App\ErrorJson'

  ## Generators

  JtcSolutions\CodeGenerator\Service\Generator\Controller\CreateControllerGenerator:
    public: true

  JtcSolutions\CodeGenerator\Service\Generator\Controller\DeleteControllerGenerator:
    public: true

  JtcSolutions\CodeGenerator\Service\Generator\Controller\DetailControllerGenerator:
    public: true

  JtcSolutions\CodeGenerator\Service\Generator\Controller\ListControllerGenerator:
    public: true

  JtcSolutions\CodeGenerator\Service\Generator\Controller\UpdateControllerGenerator:
    public: true

  JtcSolutions\CodeGenerator\Service\Generator\Dto\DtoGenerator:
    public: true

  ## Configurators

  JtcSolutions\CodeGenerator\Service\Configurator\Controller\CreateControllerConfigurator:
    public: true

  JtcSolutions\CodeGenerator\Service\Configurator\Controller\DeleteControllerConfigurator:
    public: true

  JtcSolutions\CodeGenerator\Service\Configurator\Controller\DetailControllerConfigurator:
    public: true

  JtcSolutions\CodeGenerator\Service\Configurator\Controller\ListControllerConfigurator:
    public: true

  JtcSolutions\CodeGenerator\Service\Configurator\Controller\UpdateControllerConfigurator:
    public: true

  JtcSolutions\CodeGenerator\Service\Configurator\Dto\DtoConfigurator:
    public: true

  ## Renderers

  JtcSolutions\CodeGenerator\Service\CodeRenderer\Controller\ControllerCodeRenderer:
    public: true

  JtcSolutions\CodeGenerator\Service\CodeRenderer\Dto\DtoCodeRenderer:
    public: true

  ## Writer

  JtcSolutions\CodeGenerator\Service\Writer\ControllerClassWriter:
    public: true

  JtcSolutions\CodeGenerator\Service\Writer\DtoClassWriter:
    public: true